development:
  bucket: indy-dev
  access_key_id: AKIAJB5S5DHTZDJTO34Q
  secret_access_key: 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
test:
  bucket: indy-dev
  access_key_id: AKIAJB5S5DHTZDJTO34Q
  secret_access_key: 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
production:
  bucket: indy
  access_key_id: AKIAJB5S5DHTZDJTO34Q
  secret_access_key: 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